default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: mead_project_development
  username: postgres
  password: ENV["SECRET_KEY_BASE"]

test:
  <<: *default
  database: mead_project_test
  host: localhost
  username: postgres
  password: ENV["SECRET_KEY_BASE"]

production:
  <<: *default
  database: mead_project_production
  host: localhost
  username: postgres
  password: ENV["SECRET_KEY_BASE"]
