development:
  server: "//heimdallmead.herokuapp.com/faye"
  secret_token: "mead"
test:
  server: "//heimdallmead.herokuapp.com/faye"
  secret_token: "mead"
production:
  server: "//heimdallmead.herokuapp.com/faye"
  secret_token: "mead"
  signature_expiration: 3600 # one hour
